/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dzy.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dzy.domain.App;
import com.dzy.domain.City;
import com.dzy.domain.Province;
import com.dzy.domain.University;
import com.dzy.domain.Users;
import com.dzy.service.imp.UniversityService;
import com.dzy.service.interfac.CityServiceInterface;
import com.dzy.service.interfac.ProvinceServiceInterface;
import com.dzy.service.interfac.UniversityServiceInterface;
import com.dzy.service.interfac.UserServiceInterface;
import com.dzy.struts.form.UserForm;
import com.dzy.util.MyMD5;


public class LoginAction extends DispatchAction {
	
	private UserServiceInterface userService;
	private ProvinceServiceInterface provinceService;
	private UniversityServiceInterface universityService;
	private CityServiceInterface cityService;
	public void setProvinceService(ProvinceServiceInterface provinceService) {
		this.provinceService = provinceService;
	}

	public void setUniversityService(UniversityServiceInterface universityService) {
		this.universityService = universityService;
	}

	public void setCityService(CityServiceInterface cityService) {
		this.cityService = cityService;
	}

	public void setUserService(UserServiceInterface userService) {
		this.userService = userService;
	}
	
	//他报了空指针就说明这个家伙没有set进去spring里面
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm uf=(UserForm) form;
		//System.out.println("渠道的是"+uf.getPwd());
		Users user=new Users();
		user.setUsername(uf.getUsername());
		user.setPwd(MyMD5.MD5(uf.getPwd()));
	//	System.out.println("能取出密码吗"+uf.getPwd()+uf.getUsername());
		user=userService.checkUser(user);
		if(user==null)
		{
			return mapping.findForward("loginerr");
		}else
		{
			//System.out.println("其实我想知道是不是把"+user.getEmail());
			request.getSession().setAttribute("loginuser",user);
			return mapping.findForward("loginok");
		}
	}
	
	public ActionForward register(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm uf=(UserForm) form;
	//	System.out.println("看下打"+uf.getPwd()+uf.getUniversityId());
	//	System.out.println(uf.getSex());
		Users user=new Users();
		user.setUsername(uf.getUsername());
		user.setName(uf.getName());
		user.setRegisterDate(new java.util.Date());
		user.setLoginDate(new java.util.Date());
		user.setPwd(MyMD5.MD5(uf.getPwd()));
		user.setEmail(uf.getEmail());
		user.setSex(uf.getSex());
		//得到其大学id，这样就可以根据id去查询省份id，和城市id
		Integer id=Integer.parseInt(uf.getUniversityId());
		//Integer[] id2=universityService.GetOtherIdFromUniversityId(id);
		University uy=(University) universityService.findById(University.class, id);
		//System.out.println("打出来的"+id2[0]+"&&&&&&&&&"+id2[0]);
		//user.setProvince((Province)provinceService.findById(Province.class, uy.getProvince()));
		//user.setCity((City)cityService.findById(City.class, uy.getCity()));
		user.setUniversity(uy);
		user.setProvince(uy.getProvince());
		user.setCity(uy.getCity());
	    userService.addUser(user);
		request.getSession().setAttribute("loginuser", user);
		String hql="from App";
		List<App> list=userService.executeByPage(1,12,null, hql);
		request.setAttribute("appinfo",list);
		return mapping.findForward("registerok");
	}
	
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		request.getSession().invalidate();
		return mapping.findForward("loginerr");
	}
}