/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dzy.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dzy.domain.App;
import com.dzy.domain.Appcomment;
import com.dzy.service.interfac.ShowAppServiceInterface;

/** 
 * MyEclipse Struts
 * Creation date: 03-18-2014
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class ShowAppAction extends DispatchAction {
	
	ShowAppServiceInterface showAppService=null;
	public void setShowAppService(ShowAppServiceInterface showAppService) {
		this.showAppService = showAppService;
	}
	public ActionForward showmain(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		List<App> list=showAppService.showFirstPageApp(1, 12);
		request.setAttribute("appinfo",list);
//		for(int i=0;i<list.size();i++)
//		{
//			
//			App a=list.get(i);
//			System.out.println("其实我也很想知道为什么"+a.getAppName());
//		}
		return mapping.findForward("showmain");
	}
	//这是展示app的地方
	public ActionForward showapp(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String id=request.getParameter("id");
		//System.out.println("id的大小事"+id);
		App a=(App) showAppService.findById(App.class, Integer.parseInt(id));
		request.setAttribute("appinfomation", a);
		//把评论也读出来
		
		String hql="from Appcomment where app.id=? order by id desc ";
		List<Appcomment> commentlist=showAppService.executeLastPage(hql,new Object[]{Integer.parseInt(id)},3);
		//System.out.println(commentlist.size());
		
		//下面还要把下载最多的应用读出来
		List<App> list3=showAppService.showMostDownload();
		request.setAttribute("mostdownload", list3);
		
		request.setAttribute("commentinfo", commentlist);
		return mapping.findForward("showappinfo");
	}
	
	
	public ActionForward aboutwebsite(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		return mapping.findForward("gotoaboutwebsite");
	}
	
}