/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dzy.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dzy.domain.App;
import com.dzy.domain.Users;
import com.dzy.service.interfac.AppServiceInterface;


public class TohomeAction extends DispatchAction {
	
	private AppServiceInterface appService;
	
	public void setAppService(AppServiceInterface appService) {
		this.appService = appService;
	}

	public ActionForward tohome(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//这个是到家的，到家，还要看看自己下载了什么应用啊
		Users user=(Users) request.getSession().getAttribute("loginuser");
		String hql="from Userdownapp where users.id=?";
		List list=appService.executeByPage(1,12,new Object[]{user.getId()} , hql);
		request.setAttribute("userdownappinfo", list);
		
		return mapping.findForward("tohome");
	}
	
	public ActionForward searshapp(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//搜索专用，其实是不想再增加action的数量，就用你了
		String text=request.getParameter("text");
		//System.out.println("text的只是"+text);
		String hql="from App where appName=?";
		App app=(App) appService.executeQuery(hql, new Object[]{text});
		request.setAttribute("app", app);
		return mapping.findForward("searchok");
	}
}