/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dzy.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dzy.service.interfac.ProvinceServiceInterface;
import com.dzy.service.interfac.UniversityServiceInterface;


public class ToLoginAction extends DispatchAction {
	
	ProvinceServiceInterface provinceService=null;
	UniversityServiceInterface universityService=null;
	
	public void setUniversityService(UniversityServiceInterface universityService) {
		this.universityService = universityService;
	}
	public void setProvinceService(ProvinceServiceInterface provinceService) {
		this.provinceService = provinceService;
	}
	public ActionForward tologin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("tologin");
	}
	public ActionForward toregister(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//在这里把数据取一部分出来试试看吧
		request.setAttribute("provincelist", provinceService.ShowProvince());
		request.setAttribute("unilist", universityService.ShowUniversity(new Object[]{new Integer(1)}));
		
		return mapping.findForward("toregister");
	}
	
}