/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dzy.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.dzy.domain.App;
import com.dzy.service.interfac.AppServiceInterface;
import com.dzy.struts.form.AppForm;
import com.dzy.util.MyTools;

	

public class UploadAction extends DispatchAction {
	private AppServiceInterface appService;
	//搞半天无法实例化，原来是这里出了问题，需要一个set注入呀
	
	public ActionForward gotest(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("upload");
	}
	
	public void setAppService(AppServiceInterface appService) {
		this.appService = appService;
	}

	public ActionForward uploadok(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AppForm appForm = (AppForm) form;
		FormFile mylogo=appForm.getApplogo();
		//System.out.println("取得的名称"+mylogo.getFileName());
		String newname=MyTools.uploadlogo(request, mylogo);
		String newjietu=MyTools.uploadjietu(request,appForm.getAppjietu());
		//System.out.println("新名称是"+newname);
		App app=new App();
		app.setAppDate(new java.util.Date());
	//	System.out.println("日期是"+MyTools.getimagesrc());
		app.setAppLogo(newname);
		app.setAppPhoto(newjietu);
		app.setAppSrc(MyTools.getimagesrc());
		app.setAppName(appForm.getApp_name());
		app.setAppId(appForm.getApp_id());
		app.setAppDownadd(appForm.getDownadre());
		app.setAppSpedesc(appForm.getApp_spedesc());
	//	System.out.println(request.getParameter("apptype"));
		app.setAppType(appForm.getApp_type());
		System.out.println(newjietu);
		app.setAppDesc(appForm.getApp_desc());
		appService.add(app);
		return mapping.findForward("uploadok");
	}
}